# Generated by Django 3.2.19 on 2025-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_time_spent', models.FloatField(default=0)),
            ],
        ),
    ]
