# Generated by Django 3.2.19 on 2025-01-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
