# Generated by Django 3.2.19 on 2025-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hou', '0002_auto_20250117_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_time_spent',
        ),
        migrations.AddField(
            model_name='player',
            name='task1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task4_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='task4_completed',
            field=models.BooleanField(default=False),
        ),
    ]
