# Generated by Django 3.2.19 on 2025-01-17 11:49

from django.db import migrations, models
def create_tasks(apps, schema_editor):
    Task = apps.get_model('hou', 'Task')
    tasks = [
        {
            'name': 'Task1',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': '神秘任务',
            'answer': '5'
        },
        {
            'name': 'Task2',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': '神秘任务',
            'answer': '3'
        },
        {
            'name': 'Task3',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': '神秘任务',
            'answer': '24'
        },
        {
            'name': 'Task4',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': '神秘任务',
            'answer': '4'
        }
    ]
    for task in tasks:
        Task.objects.create(**task)

class Migration(migrations.Migration):

    dependencies = [
        ('hou', '0003_auto_20250117_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='student_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
