# Generated by Django 3.2.19 on 2025-01-17 11:57

from django.db import migrations, models
def create_tasks(apps, schema_editor):
    Task = apps.get_model('hou', 'Task')
    tasks = [
        {
            'name': 'Task1',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': 'Solve the addition problem: 2 + 3',
            'answer': '5'
        },
        {
            'name': 'Task2',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': 'Solve the subtraction problem: 10 - 7',
            'answer': '3'
        },
        {
            'name': 'Task3',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': 'Solve the multiplication problem: 4 * 6',
            'answer': '24'
        },
        {
            'name': 'Task4',
            'latitude': 0.0,
            'longitude': 0.0,
            'description': 'Solve the division problem: 16 / 4',
            'answer': '4'
        }
    ]
    for task in tasks:
        Task.objects.create(**task)

class Migration(migrations.Migration):

    dependencies = [
        ('hou', '0004_auto_20250117_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(create_tasks),
    ]
